# Generated by Django 5.0.6 on 2024-06-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=55)),
                ('vote1', models.IntegerField(default=0)),
                ('option2', models.CharField(max_length=55)),
                ('vote2', models.IntegerField(default=0)),
                ('option3', models.CharField(max_length=55)),
                ('vote3', models.IntegerField(default=0)),
            ],
        ),
    ]
