# Generated by Django 5.0.6 on 2024-06-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeSubmission',
            new_name='submission',
        ),
    ]
